/**
 * Food query normalization — Layer 1 of the VegSage search architecture.
 *
 * Converts any user query (FR / DE / EN, with or without accents, with typos)
 * to the canonical English food name that USDA FoodData Central responds best to.
 *
 * Design:
 * - Alias table keys are accent-stripped, lowercase.
 * - The function strips accents from input before lookup.
 * - "œufs", "oeufs", "Oeufs", "OEUFS" all resolve to "eggs".
 * - Sorted longest-first so "salade verte" matches before "salade".
 */

// ─── Accent stripping ──────────────────────────────────────────────────────────

const ACCENT_REPLACEMENTS: [RegExp, string][] = [
  [/[àâäáã]/g,  "a"],
  [/[èéêë]/g,   "e"],
  [/[îïíì]/g,   "i"],
  [/[ôöóòõ]/g,  "o"],
  [/[ûüúù]/g,   "u"],
  [/ç/g,        "c"],
  [/ñ/g,        "n"],
  [/ß/g,        "ss"],
  [/œ/g,        "oe"],
  [/æ/g,        "ae"],
];

export function stripAccents(s: string): string {
  let r = s;
  for (const [re, rep] of ACCENT_REPLACEMENTS) r = r.replace(re, rep);
  return r;
}

// ─── Alias table ──────────────────────────────────────────────────────────────
// Keys: accent-stripped lowercase. Values: canonical English for USDA search.
// Longest-first so "salade verte" matches before "salade", "thymian" before "thym".

const _ALIASES: [string, string][] = [
  // ── FR multi-word ──────────────────────────────────────────────────────────
  ["lait de riz",           "rice milk"],
  ["lait de noisette",      "hazelnut milk"],
  ["lait de cajou",         "cashew milk"],
  ["lait de chanvre",       "hemp milk"],
  ["lait de pois",          "pea milk"],
  ["lait de macadamia",     "macadamia milk"],
  ["lait de pistache",      "pistachio milk"],
  ["lait de quinoa",        "quinoa milk"],
  ["boisson avoine",        "oat milk"],
  ["boisson soja",          "soy milk"],
  ["boisson amande",        "almond milk"],
  ["boisson riz",           "rice milk"],
  ["yaourt de soja",        "soy yogurt"],
  ["yaourt soja",           "soy yogurt"],
  ["yaourt coco",           "coconut yogurt"],
  ["yaourt avoine",         "oat yogurt"],
  ["yaourt amande",         "almond yogurt"],
  ["fromage vegetal",       "plant-based cheese"],
  ["fromage vegetalien",    "plant-based cheese"],
  ["proteines de soja",     "textured soy protein"],
  ["creme d avoine",        "oat cream"],
  ["creme de soja",         "soy cream"],
  ["creme de coco",         "coconut cream"],
  ["beurre vegetal",        "vegan butter"],
  ["haricots mungo",        "mung beans"],
  ["haricots adzuki",       "adzuki beans"],
  ["feves",                 "fava beans"],
  ["lentilles corail",      "red lentils"],
  ["lentilles rouges",      "red lentils"],
  ["pois casses",           "split peas"],
  ["sauce soja",            "soy sauce"],
  ["vinaigre de cidre",     "apple cider vinegar"],
  ["vinaigre balsamique",   "balsamic vinegar"],
  ["sirop d erable",        "maple syrup"],
  ["sirop d agave",         "agave syrup"],
  ["concentre de tomates",  "tomato paste"],
  ["sauce tomate",          "tomato sauce"],
  ["moutarde de dijon",     "dijon mustard"],
  ["jus d orange",          "orange juice"],
  ["jus de pomme",          "apple juice"],
  ["jus de tomate",         "tomato juice"],
  ["eau de coco",           "coconut water"],
  ["the vert",              "green tea"],
  ["the noir",              "black tea"],
  ["the rouge",             "rooibos"],
  ["the de rooibos",        "rooibos"],
  ["chou rouge",            "red cabbage"],
  ["chou de savoie",        "savoy cabbage"],
  ["chou de bruxelles",     "brussels sprouts"],
  ["chou rave",             "kohlrabi"],
  ["oignon vert",           "spring onion"],
  ["oignon nouveau",        "spring onion"],
  ["tomates cerises",       "cherry tomatoes"],
  ["tomates sechees",       "sun-dried tomatoes"],
  ["tomates en conserve",   "canned tomatoes"],
  ["pousses de bambou",     "bamboo shoots"],
  ["noix du bresil",        "brazil nuts"],
  ["noix de macadamia",     "macadamia nuts"],
  ["noix de pecan",         "pecans"],
  ["pignons de pin",        "pine nuts"],
  ["graines de pavot",      "poppy seeds"],
  ["flocons de mais",       "corn flakes"],
  ["son d avoine",          "oat bran"],
  ["germe de ble",          "wheat germ"],
  ["levure de biere",       "brewer's yeast"],
  ["levure nutritionnelle", "nutritional yeast"],
  ["aminos de coco",        "coconut aminos"],
  ["graisse de coco",       "coconut oil"],
  ["baies de goji",         "goji berries"],
  ["fruit de la passion",   "passion fruit"],
  ["raisins secs",          "raisins"],
  ["abricots secs",         "dried apricots"],
  ["mangue sechee",         "dried mango"],
  ["pain de seigle",        "rye bread"],
  ["pain complet",          "whole wheat bread"],
  ["pain d epautre",        "spelt bread"],
  ["farine complete",       "whole wheat flour"],
  ["farine de riz",         "rice flour"],
  ["farine d avoine",       "oat flour"],
  ["farine de pois chiches","chickpea flour"],
  ["farine de coco",        "coconut flour"],
  ["galettes de riz",       "rice cakes"],
  ["poivre noir",           "black pepper"],
  ["poivre de cayenne",     "cayenne pepper"],
  ["flocons de piment",     "chili flakes"],
  ["cannelle",              "cinnamon"],
  ["curcuma",               "turmeric"],
  ["gingembre moulu",       "ground ginger"],
  ["coriandre moulu",       "ground coriander"],
  ["paprika fume",          "smoked paprika"],
  ["salade verte",          "lettuce"],
  ["salade mixte",          "lettuce"],
  ["salade composee",       "lettuce"],
  ["salade de mais",        "corn salad"],
  ["petits pois",           "green peas"],
  ["pois chiches",          "chickpeas"],
  ["haricots verts",        "green beans"],
  ["haricots rouges",       "red kidney beans"],
  ["haricots blancs",       "white beans"],
  ["haricots noirs",        "black beans"],
  ["pommes de terre",       "potatoes"],
  ["patate douce",          "sweet potato"],
  ["patates douces",        "sweet potatoes"],
  ["graines de chia",       "chia seeds"],
  ["graines de lin",        "flaxseeds"],
  ["graines de courge",     "pumpkin seeds"],
  ["graines de tournesol",  "sunflower seeds"],
  ["lait d avoine",         "oat milk"],
  ["lait d amande",         "almond milk"],
  ["lait de coco",          "coconut milk"],
  ["lait de soja",          "soy milk"],
  ["yaourt nature",         "plain yogurt"],
  ["levure nutritionnelle", "nutritional yeast"],
  ["noix de cajou",         "cashews"],
  ["noix de coco",          "coconut"],
  ["huile d olive",         "olive oil"],
  ["huile de coco",         "coconut oil"],
  ["beurre de cacahuete",   "peanut butter"],
  ["beurre d amande",       "almond butter"],
  ["chou rouge",            "red cabbage"],
  ["pois casses",           "split peas"],
  ["pois verts",            "green peas"],
  ["pomme de terre",        "potato"],
  ["celeri rave",           "celeriac"],
  ["mache",                 "corn salad"],
  // ── FR multi-word (new foods) ─────────────────────────────────────────────
  ["chocolat chaud",             "hot chocolate"],
  ["boisson proteinee",          "protein drink"],
  ["shake proteine",             "protein drink"],
  ["confiture de fraises",       "strawberry jam"],
  ["confiture d abricots",       "apricot jam"],
  ["confiture de framboises",    "raspberry jam"],
  ["pate a tartiner aux noisettes", "hazelnut spread"],
  ["barre proteinee",            "protein bar"],
  ["barre de cereales",          "cereal bar"],
  ["tablette de chocolat",       "chocolate bar"],
  ["barre de chocolat",          "chocolate bar"],
  ["chocolat noir",              "dark chocolate"],
  ["fruits secs",                "dried fruit"],
  ["burger vegetarien",          "veggie burger"],
  ["lasagnes vegetariennes",     "vegetarian lasagna"],
  ["soupe aux legumes",          "vegetable soup"],
  ["soupe de legumes",           "vegetable soup"],
  ["soupe a la tomate",          "tomato soup"],
  ["soupe de tomates",           "tomato soup"],
  ["soupe aux lentilles",        "lentil soup"],
  ["soupe au potiron",           "pumpkin soup"],
  ["veloute de courge",          "pumpkin soup"],
  ["riz complet",                "brown rice"],
  ["riz brun",                   "brown rice"],
  ["pates completes",            "whole wheat pasta"],
  ["pates de ble entier",        "whole wheat pasta"],
  // ── DE multi-word ──────────────────────────────────────────────────────────
  ["reismilch",             "rice milk"],
  ["haselnussmilch",        "hazelnut milk"],
  ["cashewmilch",           "cashew milk"],
  ["hanfmilch",             "hemp milk"],
  ["erbsenmilch",           "pea milk"],
  ["macadamiamilch",        "macadamia milk"],
  ["hafermilch",            "oat milk"],
  ["sojamilch",             "soy milk"],
  ["mandelmilch",           "almond milk"],
  ["kokosmilch",            "coconut milk"],
  ["sojajoghurt",           "soy yogurt"],
  ["kokosjoghurt",          "coconut yogurt"],
  ["haferjoghurt",          "oat yogurt"],
  ["mandeljoghurt",         "almond yogurt"],
  ["veganer kase",          "plant-based cheese"],
  ["texturiertes sojaprotein", "textured soy protein"],
  ["sojaprotein",           "textured soy protein"],
  ["haferrahm",             "oat cream"],
  ["sojarahm",              "soy cream"],
  ["kokosrahm",             "coconut cream"],
  ["vegane butter",         "vegan butter"],
  ["mungobohnen",           "mung beans"],
  ["adzukibohnen",          "adzuki beans"],
  ["favabohnen",            "fava beans"],
  ["rote linsen",           "red lentils"],
  ["sojasosse",             "soy sauce"],
  ["tamari sosse",          "tamari"],
  ["apfelessig",            "apple cider vinegar"],
  ["balsamico essig",       "balsamic vinegar"],
  ["ahornsirup",            "maple syrup"],
  ["agavensirup",           "agave syrup"],
  ["tomatenmark",           "tomato paste"],
  ["tomatensauce",          "tomato sauce"],
  ["dijonsenf",             "dijon mustard"],
  ["orangensaft",           "orange juice"],
  ["apfelsaft",             "apple juice"],
  ["tomatensaft",           "tomato juice"],
  ["kokoswasser",           "coconut water"],
  ["gruner tee",            "green tea"],
  ["schwarzer tee",         "black tea"],
  ["rooibos tee",           "rooibos"],
  ["rotkohl",               "red cabbage"],
  ["blaukraut",             "red cabbage"],
  ["wirsing",               "savoy cabbage"],
  ["fruhlingsszwiebeln",    "spring onion"],
  ["schalotte",             "shallot"],
  ["schalotten",            "shallot"],
  ["kirschtomaten",         "cherry tomatoes"],
  ["cocktailtomaten",       "cherry tomatoes"],
  ["getrocknete tomaten",   "sun-dried tomatoes"],
  ["dosentomaten",          "canned tomatoes"],
  ["bambussprossen",        "bamboo shoots"],
  ["paranuss",              "brazil nuts"],
  ["paranüsse",             "brazil nuts"],
  ["macadamianusse",        "macadamia nuts"],
  ["macadamianüsse",        "macadamia nuts"],
  ["pekannusse",            "pecans"],
  ["pekannüsse",            "pecans"],
  ["pinienkerne",           "pine nuts"],
  ["mohnsamen",             "poppy seeds"],
  ["maisflocken",           "corn flakes"],
  ["haferkleie",            "oat bran"],
  ["weizenkeime",           "wheat germ"],
  ["bierhefe",              "brewer's yeast"],
  ["kokosaminosauren",      "coconut aminos"],
  ["kokosol",               "coconut oil"],
  ["gojibeeren",            "goji berries"],
  ["goji beeren",           "goji berries"],
  ["maracuja",              "passion fruit"],
  ["passionsfrucht",        "passion fruit"],
  ["rosinen",               "raisins"],
  ["getrocknete aprikosen", "dried apricots"],
  ["getrocknete mango",     "dried mango"],
  ["vollkornmehl",          "whole wheat flour"],
  ["reismehl",              "rice flour"],
  ["hafermehl",             "oat flour"],
  ["kichererbsenmehl",      "chickpea flour"],
  ["kokosmehl",             "coconut flour"],
  ["reiswaffeln",           "rice cakes"],
  ["schwarzer pfeffer",     "black pepper"],
  ["cayennepfeffer",        "cayenne pepper"],
  ["chiliflocken",          "chili flakes"],
  ["zimt",                  "cinnamon"],
  ["kurkuma",               "turmeric"],
  ["gemahlener ingwer",     "ground ginger"],
  ["gemahlener koriander",  "ground coriander"],
  ["geraucherter paprika",  "smoked paprika"],
  ["geraücherter paprika",  "smoked paprika"],
  ["gruner salat",          "lettuce"],
  ["gemischter salat",      "lettuce"],
  ["rote bohnen",           "red kidney beans"],
  ["grune bohnen",          "green beans"],
  ["weisse bohnen",         "white beans"],
  ["schwarze bohnen",       "black beans"],
  ["rote bete",             "beet"],
  ["sussekartoffel",        "sweet potato"],
  ["rosenkohl",             "brussels sprouts"],
  ["grunkohl",              "kale"],
  // ── DE multi-word (new foods) ─────────────────────────────────────────────
  ["heisser kakao",              "hot chocolate"],
  ["proteindrink",               "protein drink"],
  ["eiweissgetrank",             "protein drink"],
  ["erdbeermarmelade",           "strawberry jam"],
  ["aprikosenmarmelade",         "apricot jam"],
  ["himbeermarmelade",           "raspberry jam"],
  ["haselnusscreme",             "hazelnut spread"],
  ["nussnougatcreme",            "hazelnut spread"],
  ["proteinriegel",              "protein bar"],
  ["musliriegel",                "cereal bar"],
  ["musli riegel",               "cereal bar"],
  ["getreideriegel",             "cereal bar"],
  ["schokoladenriegel",          "chocolate bar"],
  ["dunkle schokolade",          "dark chocolate"],
  ["zartbitterschokolade",       "dark chocolate"],
  ["trockenfruchte",             "dried fruit"],
  ["dorrfruchte",                "dried fruit"],
  ["gemuseburger",               "veggie burger"],
  ["vegetarischer burger",       "veggie burger"],
  ["vegetarische lasagne",       "vegetarian lasagna"],
  ["gemusesuppe",                "vegetable soup"],
  ["tomatensuppe",               "tomato soup"],
  ["linsensuppe",                "lentil soup"],
  ["kurbissuppe",                "pumpkin soup"],
  ["vollkornreis",               "brown rice"],
  ["brauner reis",               "brown rice"],
  ["vollkornnudeln",             "whole wheat pasta"],
  ["vollkornbrot",               "whole wheat bread"],
  // ── FR cooking states (multi-word) ────────────────────────────────────────
  ["en conserve",           "canned"],
  ["a la vapeur",           "steamed"],
  ["au four",               "baked"],
  // ── FR single words ────────────────────────────────────────────────────────
  ["oeufs",        "eggs"],       // œufs → oeufs after accent strip
  ["oeuf",         "egg"],        // œuf  → oeuf after accent strip
  ["yoghourt",     "yogurt"],     // alternate spelling
  ["yougourt",     "yogurt"],     // typo
  ["yaourt",       "yogurt"],     // standard French
  ["lentilles",    "lentils"],
  ["lentille",     "lentil"],
  ["salade",       "lettuce"],
  ["laitue",       "lettuce"],
  ["epinards",     "spinach"],
  ["courgettes",   "zucchini"],
  ["courgette",    "zucchini"],
  ["aubergine",    "eggplant"],
  ["poivrons",     "bell peppers"],
  ["poivron",      "bell pepper"],
  ["champignons",  "mushrooms"],
  ["champignon",   "mushroom"],
  ["oignons",      "onions"],
  ["oignon",       "onion"],
  ["carottes",     "carrots"],
  ["carotte",      "carrot"],
  ["tomates",      "tomatoes"],
  ["tomate",       "tomato"],
  ["concombre",    "cucumber"],
  ["chou-fleur",   "cauliflower"],
  ["brocoli",      "broccoli"],
  ["brocolis",     "broccoli"],
  ["celeri",       "celery"],
  ["asperges",     "asparagus"],
  ["asperge",      "asparagus"],
  ["artichaut",    "artichoke"],
  ["poireaux",     "leeks"],
  ["poireau",      "leek"],
  ["radis",        "radish"],
  ["navet",        "turnip"],
  ["betterave",    "beet"],
  ["avocats",      "avocados"],
  ["avocat",       "avocado"],
  ["pommes",       "apples"],
  ["pomme",        "apple"],
  ["poires",       "pears"],
  ["poire",        "pear"],
  ["bananes",      "bananas"],
  ["banane",       "banana"],
  ["fraises",      "strawberries"],
  ["fraise",       "strawberry"],
  ["framboises",   "raspberries"],
  ["framboise",    "raspberry"],
  ["myrtilles",    "blueberries"],
  ["myrtille",     "blueberry"],
  ["raisins",      "grapes"],
  ["raisin",       "grapes"],
  ["cerises",      "cherries"],
  ["cerise",       "cherry"],
  ["peches",       "peaches"],
  ["peche",        "peach"],
  ["abricots",     "apricots"],
  ["abricot",      "apricot"],
  ["mangues",      "mangoes"],
  ["mangue",       "mango"],
  ["ananas",       "pineapple"],
  ["pasteque",     "watermelon"],
  ["melon",        "melon"],
  ["citron",       "lemon"],
  ["oranges",      "oranges"],
  ["orange",       "orange"],
  ["pamplemousse", "grapefruit"],
  ["kiwi",         "kiwi"],
  ["figues",       "figs"],
  ["figue",        "fig"],
  ["dattes",       "dates"],
  ["datte",        "date"],
  ["noix",         "walnuts"],
  ["amandes",      "almonds"],
  ["amande",       "almond"],
  ["noisettes",    "hazelnuts"],
  ["noisette",     "hazelnut"],
  ["cacahuetes",   "peanuts"],
  ["cacahuete",    "peanut"],
  ["riz",          "rice"],
  ["pates",        "pasta"],
  ["avoine",       "oats"],
  ["orge",         "barley"],
  ["sarrasin",     "buckwheat"],
  ["millet",       "millet"],
  ["pain",         "bread"],
  ["farine",       "flour"],
  ["fromage",      "cheese"],
  ["beurre",       "butter"],
  ["creme",        "cream"],
  ["lait",         "milk"],
  ["fenouil",      "fennel"],
  ["persil",       "parsley"],
  ["basilic",      "basil"],
  ["menthe",       "mint"],
  ["thym",         "thyme"],
  ["romarin",      "rosemary"],
  ["coriandre",    "coriander"],
  ["cornichons",   "pickles"],
  ["cornichon",    "pickle"],
  ["soupe",        "soup"],
  ["mais",         "corn"],
  ["surgelees",    "frozen"],
  ["surgeles",     "frozen"],
  ["cuites",       "cooked"],
  ["cuits",        "cooked"],
  ["crue",         "raw"],
  ["cru",          "raw"],
  ["sechees",      "dried"],
  ["seches",       "dried"],
  // ── FR single words (new foods) ───────────────────────────────────────────
  ["gateau",       "cake"],
  ["biscuits",     "cookies"],
  ["biscuit",      "cookie"],
  ["bretzels",     "pretzels"],
  ["bretzel",      "pretzel"],
  ["cafe",         "coffee"],
  // ── DE single words ────────────────────────────────────────────────────────
  ["linsen",       "lentils"],
  ["erbsen",       "green peas"],
  ["kichererbsen", "chickpeas"],
  ["spinat",       "spinach"],
  ["brokkoli",     "broccoli"],
  ["blumenkohl",   "cauliflower"],
  ["karotten",     "carrots"],
  ["karotte",      "carrot"],
  ["tomaten",      "tomatoes"],
  ["kartoffeln",   "potatoes"],
  ["kartoffel",    "potato"],
  ["paprika",      "bell pepper"],
  ["pilze",        "mushrooms"],
  ["zwiebeln",     "onions"],
  ["zwiebel",      "onion"],
  ["knoblauch",    "garlic"],
  ["gurke",        "cucumber"],
  ["salat",        "lettuce"],
  ["kurbis",       "pumpkin"],
  ["fenchel",      "fennel"],
  ["mangold",      "swiss chard"],
  ["sojabohnen",   "soybeans"],
  ["eier",         "eggs"],
  ["joghurt",      "yogurt"],
  ["jogurt",       "yogurt"],
  ["milch",        "milk"],
  ["kase",         "cheese"],
  ["butter",       "butter"],
  ["haferflocken", "oatmeal"],
  ["hafer",        "oats"],
  ["reis",         "rice"],
  ["nudeln",       "pasta"],
  ["walnusse",     "walnuts"],
  ["mandeln",      "almonds"],
  ["haselnusse",   "hazelnuts"],
  ["erdnusse",     "peanuts"],
  ["schokolade",   "chocolate"],
  ["honig",        "honey"],
  ["suppe",        "soup"],
  ["essiggurken",  "pickles"],
  ["essiggurke",   "pickle"],
  ["petersilie",   "parsley"],
  ["basilikum",    "basil"],
  ["thymian",      "thyme"],
  ["rosmarin",     "rosemary"],
  ["koriander",    "coriander"],
  ["minze",        "mint"],
  ["tofu",         "tofu"],
  ["tempeh",       "tempeh"],
  ["seitan",       "seitan"],
  ["miso",         "miso"],
  ["natto",        "natto"],
  ["jackfrucht",   "jackfruit"],
  ["lupinen",      "lupins"],
  ["spirulina",    "spirulina"],
  ["chlorella",    "chlorella"],
  ["moringa",      "moringa"],
  ["matcha",       "matcha"],
  ["kombucha",     "kombucha"],
  ["granola",      "granola"],
  ["muesli",       "muesli"],
  ["musli",        "muesli"],
  ["müsli",        "muesli"],
  ["popcorn",      "popcorn"],
  ["falafel",      "falafel"],
  ["hummus",       "hummus"],
  ["guacamole",    "guacamole"],
  ["tzatziki",     "tzatziki"],
  ["tahini",       "tahini"],
  ["harissa",      "harissa"],
  ["kimchi",       "kimchi"],
  ["sauerkraut",   "sauerkraut"],
  ["mozzarella",   "mozzarella"],
  ["parmesan",     "parmesan"],
  ["gouda",        "gouda"],
  ["ricotta",      "ricotta"],
  ["huttenkase",   "cottage cheese"],
  ["frischkase",   "cream cheese"],
  ["ziegenkase",   "goat cheese"],
  ["kefir",        "kefir"],
  ["sahne",        "cream"],
  ["saure sahne",  "sour cream"],
  ["schmand",      "sour cream"],
  ["quark",        "quark"],
  ["paneer",       "paneer"],
  ["hirse",        "millet"],
  ["amaranth",     "amaranth"],
  ["dinkel",       "spelt"],
  ["teff",         "teff"],
  ["couscous",     "couscous"],
  ["polenta",      "polenta"],
  ["bulgur",       "bulgur"],
  ["grieß",        "semolina"],
  ["griess",       "semolina"],
  ["kamut",        "kamut"],
  ["sorghum",      "sorghum"],
  ["pastinake",    "parsnip"],
  ["rube",         "turnip"],
  ["rübe",         "turnip"],
  ["kohlrabi",     "kohlrabi"],
  ["okra",         "okra"],
  ["gombo",        "okra"],
  ["endivie",      "endive"],
  ["chickoree",    "endive"],
  ["brunnenkresse","watercress"],
  ["radicchio",    "radicchio"],
  ["pak choi",     "pak choi"],
  ["bok choy",     "pak choi"],
  ["daikon",       "daikon"],
  ["wasabi",       "wasabi"],
  ["grapefruit",   "grapefruit"],
  ["wassermelone", "watermelon"],
  ["melone",       "melon"],
  ["feige",        "fig"],
  ["aprikose",     "apricot"],
  ["pfirsich",     "peach"],
  ["pflaume",      "plum"],
  ["nektarine",    "nectarine"],
  ["granatapfel",  "pomegranate"],
  ["papaya",       "papaya"],
  ["lychee",       "lychee"],
  ["litchi",       "lychee"],
  ["limette",      "lime"],
  ["ananas",       "pineapple"],
  ["drachenfrucht","dragon fruit"],
  ["pitaya",       "dragon fruit"],
  ["pistazien",    "pistachios"],
  ["pistazie",     "pistachios"],
  ["pekannusse",   "pecans"],
  ["mohnsamen",    "poppy seeds"],
  ["thymian",      "thyme"],
  ["rosmarin",     "rosemary"],
  ["oregano",      "oregano"],
  ["salbei",       "sage"],
  ["dill",         "dill"],
  ["schnittlauch", "chives"],
  ["kreuzkummel",  "cumin"],
  ["kreuzkümel",   "cumin"],
  ["koriander",    "coriander"],
  ["nelken",       "cloves"],
  ["muskatnuss",   "nutmeg"],
  ["kardamom",     "cardamom"],
  ["vanille",      "vanilla"],
  ["ingwer",       "ginger"],
  ["ei",           "egg"],
  ["gekocht",      "cooked"],
  ["gefroren",     "frozen"],
  ["getrocknet",   "dried"],
  ["roh",          "raw"],
  // ── FR single words (additional) ─────────────────────────────────────────
  ["miso",         "miso"],
  ["kimchi",       "kimchi"],
  ["tempeh",       "tempeh"],
  ["seitan",       "seitan"],
  ["jackfruit",    "jackfruit"],
  ["spiruline",    "spirulina"],
  ["granola",      "granola"],
  ["muesli",       "muesli"],
  ["falafel",      "falafel"],
  ["houmous",      "hummus"],
  ["guacamole",    "guacamole"],
  ["tzatziki",     "tzatziki"],
  ["kefir",        "kefir"],
  ["quark",        "quark"],
  ["paneer",       "paneer"],
  ["millet",       "millet"],
  ["amarante",     "amaranth"],
  ["epautre",      "spelt"],
  ["epeautre",     "spelt"],
  ["couscous",     "couscous"],
  ["polenta",      "polenta"],
  ["boulgour",     "bulgur"],
  ["semoule",      "semolina"],
  ["kamut",        "kamut"],
  ["panais",       "parsnip"],
  ["navet",        "turnip"],
  ["chou-rave",    "kohlrabi"],
  ["gombo",        "okra"],
  ["endive",       "endive"],
  ["cresson",      "watercress"],
  ["radicchio",    "radicchio"],
  ["daikon",       "daikon"],
  ["wasabi",       "wasabi"],
  ["pamplemousse", "grapefruit"],
  ["pasteque",     "watermelon"],
  ["figue",        "fig"],
  ["figues",       "figs"],
  ["abricot",      "apricot"],
  ["abricots",     "apricots"],
  ["peche",        "peach"],
  ["prune",        "plum"],
  ["nectarine",    "nectarine"],
  ["grenade",      "pomegranate"],
  ["papaye",       "papaya"],
  ["litchi",       "lychee"],
  ["pistaches",    "pistachios"],
  ["pistache",     "pistachio"],
  ["cannelle",     "cinnamon"],
  ["curcuma",      "turmeric"],
  ["cumin",        "cumin"],
  ["oregano",      "oregano"],
  ["sauge",        "sage"],
  ["aneth",        "dill"],
  ["ciboulette",   "chives"],
  ["clous de girofle", "cloves"],
  ["muscade",      "nutmeg"],
  ["cardamome",    "cardamom"],
  ["vanille",      "vanilla"],
  ["gingembre",    "ginger"],
  // ── EN: common user variants / typos ────────────────────────────────────────
  ["soy yogurt",   "soy yogurt"],
  ["soya yogurt",  "soy yogurt"],
  ["oat yogurt",   "oat yogurt"],
  ["almond yogurt","almond yogurt"],
  ["coconut yogurt","coconut yogurt"],
  ["oat milk",     "oat milk"],
  ["rice milk",    "rice milk"],
  ["hazelnut milk","hazelnut milk"],
  ["cashew milk",  "cashew milk"],
  ["hemp milk",    "hemp milk"],
  ["pea milk",     "pea milk"],
  ["tvp",          "textured soy protein"],
  ["tsp",          "textured soy protein"],
  ["yoghrt",       "yogurt"],
  ["linzen",       "lentils"],
  ["lenzen",       "lentils"],
  ["lentile",      "lentils"],
  ["spinache",     "spinach"],
  // ── DE single words (new foods) ───────────────────────────────────────────
  ["kekse",        "cookies"],
  ["platzchen",    "cookies"],
  ["brezeln",      "pretzels"],
  ["brezel",       "pretzel"],
  ["kaffee",       "coffee"],
];

// Sort longest-first to guarantee longest match wins
const SORTED_ALIASES = [..._ALIASES].sort((a, b) => b[0].length - a[0].length);

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * Normalize a user food query to a canonical English food name.
 *
 * Steps:
 * 1. Lowercase + strip accents  (œufs → oeufs, pêche → peche)
 * 2. Exact phrase match         (oeufs → eggs)
 * 3. Partial phrase replacement (lentilles cuites → lentils cooked)
 * 4. Fallback: accent-stripped form
 *
 * @example
 * normalizeFoodQuery("lentilles")    // → "lentils"
 * normalizeFoodQuery("œufs")        // → "eggs"
 * normalizeFoodQuery("oeufs")       // → "eggs"
 * normalizeFoodQuery("yoghourt")    // → "yogurt"
 * normalizeFoodQuery("salade verte")// → "lettuce"
 * normalizeFoodQuery("fenouil")     // → "fennel"
 */
export function normalizeFoodQuery(query: string): string {
  if (!query.trim()) return "";
  const normalized = stripAccents(query.toLowerCase().trim());

  // 1. Exact full-phrase match (fastest path)
  for (const [alias, canonical] of SORTED_ALIASES) {
    if (normalized === alias) return canonical;
  }

  // 2. Partial phrase replacement — longest match wins, single pass
  let result = normalized;
  for (const [alias, canonical] of SORTED_ALIASES) {
    if (result.includes(alias)) {
      result = result.replace(alias, canonical).trim();
      break;
    }
  }

  return result;
}

// ─── Levenshtein distance ─────────────────────────────────────────────────────

export function levenshtein(a: string, b: string): number {
  if (a === b) return 0;
  if (a.length === 0) return b.length;
  if (b.length === 0) return a.length;

  let prev = Array.from({ length: b.length + 1 }, (_, i) => i);
  for (let i = 1; i <= a.length; i++) {
    const curr: number[] = [i];
    for (let j = 1; j <= b.length; j++) {
      curr[j] =
        a[i - 1] === b[j - 1]
          ? prev[j - 1]
          : 1 + Math.min(prev[j], curr[j - 1], prev[j - 1]);
    }
    prev = curr;
  }
  return prev[b.length];
}

/**
 * Returns true if `query` is within Levenshtein distance of `target`.
 * Threshold: 1 for ≤5 chars, 2 for ≤8, 3 for longer.
 */
export function fuzzyMatch(query: string, target: string): boolean {
  if (query === target) return true;
  const threshold = query.length <= 5 ? 1 : query.length <= 8 ? 2 : 3;
  return levenshtein(query, target) <= threshold;
}

/**
 * Fuzzy-normalize: if normalizeFoodQuery returns the original query unchanged
 * (no alias matched), try fuzzy matching against all alias keys.
 * Returns the canonical for the best fuzzy match, or the original query.
 */
export function fuzzyNormalizeFoodQuery(query: string): string {
  const direct = normalizeFoodQuery(query);
  // If the query was translated, use that result
  if (direct !== query.toLowerCase().trim() && direct !== stripAccents(query.toLowerCase().trim())) {
    return direct;
  }

  const normalized = stripAccents(query.toLowerCase().trim());
  let bestCanonical: string | null = null;
  let bestDist = Infinity;

  for (const [alias, canonical] of SORTED_ALIASES) {
    const dist = levenshtein(normalized, alias);
    const threshold = normalized.length <= 5 ? 1 : normalized.length <= 8 ? 2 : 3;
    if (dist <= threshold && dist < bestDist) {
      bestDist = dist;
      bestCanonical = canonical;
    }
  }

  return bestCanonical ?? direct;
}
